import { EventModel, Organization, UserProfile } from '../types';
import { calculateEqualSplits, getMemberColor } from './calculations';

export const DEMO_USER: UserProfile = {
  id: 'usr-eren-01',
  name: 'Eren',
  email: 'eren.yeager@expenso.app',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
  color: '#10B981',
  role: 'finance_manager',
};

export const DEMO_ORGANIZATION: Organization = {
  id: 'org-uce-01',
  name: 'University College of Engineering',
  type: 'College',
  code: 'UCE2026',
};

export function createTechnovaDemoEvent(): EventModel {
  const eventId = 'evt-technova-2026';

  const teams = [
    { id: 'team-food', eventId, name: 'Food & Catering', budget: 70000, leadMemberId: 'mem-priya', leadMemberName: 'Priya' },
    { id: 'team-transport', eventId, name: 'Transport & Travel', budget: 40000, leadMemberId: 'mem-kumar', leadMemberName: 'Kumar' },
    { id: 'team-hospitality', eventId, name: 'Hospitality & Stay', budget: 50000, leadMemberId: 'mem-divya', leadMemberName: 'Divya' },
    { id: 'team-decoration', eventId, name: 'Stage & Decoration', budget: 25000, leadMemberId: 'mem-arun', leadMemberName: 'Arun' },
    { id: 'team-technical', eventId, name: 'Technical & Sound', budget: 35000, leadMemberId: 'mem-eren', leadMemberName: 'Eren' },
    { id: 'team-marketing', eventId, name: 'Marketing & Banners', budget: 15000, leadMemberId: 'mem-bala', leadMemberName: 'Bala' },
  ];

  const members = [
    {
      id: 'mem-eren',
      eventId,
      userId: DEMO_USER.id,
      name: 'Eren (Finance Lead)',
      email: 'eren@expenso.app',
      color: getMemberColor(0),
      role: 'finance_manager' as const,
      teamId: 'team-technical',
      teamName: 'Technical & Sound',
      joinedAt: '2026-09-01',
    },
    {
      id: 'mem-arun',
      eventId,
      name: 'Arun',
      email: 'arun@college.edu',
      color: getMemberColor(1),
      role: 'team_lead' as const,
      teamId: 'team-decoration',
      teamName: 'Stage & Decoration',
      joinedAt: '2026-09-01',
    },
    {
      id: 'mem-priya',
      eventId,
      name: 'Priya',
      email: 'priya@college.edu',
      color: getMemberColor(2),
      role: 'team_lead' as const,
      teamId: 'team-food',
      teamName: 'Food & Catering',
      joinedAt: '2026-09-01',
    },
    {
      id: 'mem-divya',
      eventId,
      name: 'Divya',
      email: 'divya@college.edu',
      color: getMemberColor(3),
      role: 'team_lead' as const,
      teamId: 'team-hospitality',
      teamName: 'Hospitality & Stay',
      joinedAt: '2026-09-02',
    },
    {
      id: 'mem-kumar',
      eventId,
      name: 'Kumar',
      email: 'kumar@college.edu',
      color: getMemberColor(4),
      role: 'event_admin' as const,
      teamId: 'team-transport',
      teamName: 'Transport & Travel',
      joinedAt: '2026-09-01',
    },
    {
      id: 'mem-bala',
      eventId,
      name: 'Bala',
      email: 'bala@college.edu',
      color: getMemberColor(5),
      role: 'member' as const,
      teamId: 'team-marketing',
      teamName: 'Marketing & Banners',
      joinedAt: '2026-09-03',
    },
    {
      id: 'mem-rahul',
      eventId,
      name: 'Rahul',
      email: 'rahul@college.edu',
      color: getMemberColor(6),
      role: 'member' as const,
      teamId: 'team-technical',
      teamName: 'Technical & Sound',
      joinedAt: '2026-09-04',
    },
  ];

  const incomeRecords = [
    {
      id: 'inc-1',
      eventId,
      amount: 100000,
      source: 'University Treasury Grant',
      category: 'College Funding' as const,
      date: '2026-09-10',
      description: 'Official college event grant allocation approved by Dean',
      addedBy: 'Kumar',
      status: 'received' as const,
      createdAt: '2026-09-10T10:00:00Z',
    },
    {
      id: 'inc-2',
      eventId,
      amount: 75000,
      source: 'TCS & Infosys Platinum Title Sponsorship',
      category: 'Sponsorship' as const,
      date: '2026-09-15',
      description: 'Title sponsor cheque cleared for TECHNOVA 2026',
      addedBy: 'Eren',
      status: 'received' as const,
      createdAt: '2026-09-15T14:30:00Z',
    },
    {
      id: 'inc-3',
      eventId,
      amount: 45000,
      source: 'Participant Registration Portal (300 Teams)',
      category: 'Registration Fees' as const,
      date: '2026-09-20',
      description: 'Online registration fees collected from participating colleges',
      addedBy: 'Eren',
      status: 'received' as const,
      createdAt: '2026-09-20T18:00:00Z',
    },
    {
      id: 'inc-4',
      eventId,
      amount: 30000,
      source: 'Food & Game Stalls Auction (12 Vendors)',
      category: 'Stall Fees' as const,
      date: '2026-09-22',
      description: 'Stall layout lease deposits collected from vendor stalls',
      addedBy: 'Priya',
      status: 'received' as const,
      createdAt: '2026-09-22T09:00:00Z',
    },
  ];

  const budgets = [
    { id: 'bgt-1', eventId, category: 'Food', allocatedAmount: 70000, teamId: 'team-food', teamName: 'Food & Catering' },
    { id: 'bgt-2', eventId, category: 'Transport', allocatedAmount: 40000, teamId: 'team-transport', teamName: 'Transport & Travel' },
    { id: 'bgt-3', eventId, category: 'Accommodation', allocatedAmount: 50000, teamId: 'team-hospitality', teamName: 'Hospitality & Stay' },
    { id: 'bgt-4', eventId, category: 'Decoration', allocatedAmount: 25000, teamId: 'team-decoration', teamName: 'Stage & Decoration' },
    { id: 'bgt-5', eventId, category: 'Technical', allocatedAmount: 35000, teamId: 'team-technical', teamName: 'Technical & Sound' },
    { id: 'bgt-6', eventId, category: 'Marketing', allocatedAmount: 15000, teamId: 'team-marketing', teamName: 'Marketing & Banners' },
    { id: 'bgt-7', eventId, category: 'Emergency', allocatedAmount: 15000 },
  ];

  const allMembersForSplit = members.map((m) => ({ id: m.id, name: m.name }));
  const getSplits = (amt: number) => calculateEqualSplits(amt, allMembersForSplit);

  const expenses = [
    {
      id: 'exp-tn-1',
      eventId,
      amount: 61200,
      currency: 'INR',
      merchant: 'Annapoorna Grand Caterers',
      category: 'Food',
      teamId: 'team-food',
      teamName: 'Food & Catering',
      date: '2026-09-24',
      description: 'Lunch buffet & refreshment catering for 450 participants and VIP guests',
      notes: 'GST Invoice #AGC-992 attached. Paid directly from Event Wallet.',
      paidByMemberId: 'mem-priya',
      paidByMemberName: 'Priya',
      paymentSource: 'event_money' as const,
      approvalStatus: 'approved' as const,
      splitMethod: 'equal' as const,
      splits: getSplits(61200),
      ocrData: {
        merchant: 'Annapoorna Grand Caterers',
        amount: 61200,
        date: '2026-09-24',
        tax: 5200,
        category: 'Food',
        items: [
          { name: 'Veg Special Buffet (x450)', price: 54000, quantity: 450 },
          { name: 'Evening Tea & Snacks (x450)', price: 7200, quantity: 450 },
        ],
      },
      createdBy: 'Priya',
      createdAt: '2026-09-24T12:30:00Z',
      updatedAt: '2026-09-24T12:30:00Z',
    },
    {
      id: 'exp-tn-2',
      eventId,
      amount: 28400,
      currency: 'INR',
      merchant: 'Sri Krishna Stage Decorators',
      category: 'Decoration',
      teamId: 'team-decoration',
      teamName: 'Stage & Decoration',
      date: '2026-09-23',
      description: 'Main auditorium LED backdrop setup, flower garlands & entrance archway',
      notes: 'Stage backdrop exceeded initial estimate due to extra LED wall panel.',
      paidByMemberId: 'mem-arun',
      paidByMemberName: 'Arun',
      paymentSource: 'advance' as const,
      advanceId: 'adv-arun-01',
      approvalStatus: 'approved' as const,
      splitMethod: 'equal' as const,
      splits: getSplits(28400),
      ocrData: {
        merchant: 'Sri Krishna Stage Decorators',
        amount: 28400,
        date: '2026-09-23',
        tax: 2400,
        category: 'Decoration',
      },
      createdBy: 'Arun',
      createdAt: '2026-09-23T18:00:00Z',
      updatedAt: '2026-09-23T18:00:00Z',
    },
    {
      id: 'exp-tn-3',
      eventId,
      amount: 25000,
      currency: 'INR',
      merchant: 'SoundPro Audio Systems',
      category: 'Technical',
      teamId: 'team-technical',
      teamName: 'Technical & Sound',
      date: '2026-09-23',
      description: 'JBL Line Array sound system, wireless mics & DJ console rental for 2 days',
      notes: '2-day rental agreement with technician on standby.',
      paidByMemberId: 'mem-eren',
      paidByMemberName: 'Eren (Finance Lead)',
      paymentSource: 'event_money' as const,
      approvalStatus: 'approved' as const,
      splitMethod: 'equal' as const,
      splits: getSplits(25000),
      createdBy: 'Eren',
      createdAt: '2026-09-23T14:00:00Z',
      updatedAt: '2026-09-23T14:00:00Z',
    },
    {
      id: 'exp-tn-4',
      eventId,
      amount: 3500,
      currency: 'INR',
      merchant: 'Hotel Residency VIP Hospitality',
      category: 'Accommodation',
      teamId: 'team-hospitality',
      teamName: 'Hospitality & Stay',
      date: '2026-09-24',
      description: 'Welcome bouquet, fruit basket & dinner for Chief Guest Dr. Ramesh',
      notes: 'Paid out of personal money by Divya. Pending reimbursement.',
      paidByMemberId: 'mem-divya',
      paidByMemberName: 'Divya',
      paymentSource: 'personal_money' as const,
      approvalStatus: 'submitted' as const,
      approvalThresholdNote: 'Finance Manager Approval Needed (₹3,500)',
      splitMethod: 'equal' as const,
      splits: getSplits(3500),
      createdBy: 'Divya',
      createdAt: '2026-09-24T08:15:00Z',
      updatedAt: '2026-09-24T08:15:00Z',
    },
    {
      id: 'exp-tn-5',
      eventId,
      amount: 12500,
      currency: 'INR',
      merchant: 'PrintHub Flex Printers',
      category: 'Marketing',
      teamId: 'team-marketing',
      teamName: 'Marketing & Banners',
      date: '2026-09-22',
      description: '100 vinyl flex banners, 500 ID cards & lanyards for volunteers',
      notes: 'Invoice attached. Approved by Finance Manager.',
      paidByMemberId: 'mem-bala',
      paidByMemberName: 'Bala',
      paymentSource: 'event_money' as const,
      approvalStatus: 'approved' as const,
      splitMethod: 'equal' as const,
      splits: getSplits(12500),
      createdBy: 'Bala',
      createdAt: '2026-09-22T16:00:00Z',
      updatedAt: '2026-09-22T16:00:00Z',
    },
  ];

  const advances = [
    {
      id: 'adv-arun-01',
      eventId,
      memberId: 'mem-arun',
      memberName: 'Arun',
      teamId: 'team-decoration',
      teamName: 'Stage & Decoration',
      amountReceived: 30000,
      amountSpent: 28400,
      returnedAmount: 1600,
      purpose: 'Stage decoration advance for main hall and archway setup',
      date: '2026-09-21',
      status: 'settled' as const,
      notes: 'Returned balance ₹1,600 to treasury on Sept 24.',
      createdAt: '2026-09-21T10:00:00Z',
    },
    {
      id: 'adv-kumar-01',
      eventId,
      memberId: 'mem-kumar',
      memberName: 'Kumar',
      teamId: 'team-transport',
      teamName: 'Transport & Travel',
      amountReceived: 20000,
      amountSpent: 12000,
      returnedAmount: 0,
      purpose: 'Bus fuel & driver bata advance for college buses',
      date: '2026-09-22',
      status: 'partially_settled' as const,
      notes: '₹8,000 remaining advance balance.',
      createdAt: '2026-09-22T11:00:00Z',
    },
  ];

  const reimbursements = [
    {
      id: 'rem-divya-01',
      eventId,
      expenseId: 'exp-tn-4',
      memberId: 'mem-divya',
      memberName: 'Divya',
      amount: 3500,
      status: 'pending' as const,
      date: '2026-09-24',
      notes: 'Chief guest VIP room & dinner paid with personal UPI card.',
      createdAt: '2026-09-24T08:15:00Z',
    },
  ];

  const vendors = [
    {
      id: 'vnd-1',
      eventId,
      name: 'ABC Travels & Bus Service',
      contact: '+91 98765 43210 (Rajesh)',
      category: 'Transport',
      totalContract: 32000,
      paidAmount: 20000,
      pendingAmount: 12000,
      dueDate: '2026-09-28',
      status: 'partial' as const,
      notes: '3 AC Volvo buses for college pickup & drop',
      createdAt: '2026-09-18T10:00:00Z',
    },
    {
      id: 'vnd-2',
      eventId,
      name: 'SoundPro Audio Systems',
      contact: '+91 91234 56789 (Vikram)',
      category: 'Technical',
      totalContract: 25000,
      paidAmount: 25000,
      pendingAmount: 0,
      dueDate: '2026-09-23',
      status: 'paid' as const,
      notes: 'Paid in full on Sept 23',
      createdAt: '2026-09-19T11:00:00Z',
    },
  ];

  const auditLogs = [
    {
      id: 'aud-1',
      eventId,
      timestamp: '2026-09-24 12:30',
      actorName: 'Priya',
      actorRole: 'team_lead' as const,
      action: 'EXPENSE_ADDED',
      details: 'Added Food expense of ₹61,200 for Annapoorna Grand Caterers',
    },
    {
      id: 'aud-2',
      eventId,
      timestamp: '2026-09-24 10:15',
      actorName: 'Eren (Finance Lead)',
      actorRole: 'finance_manager' as const,
      action: 'BUDGET_UPDATED',
      details: 'Updated Stage & Decoration team budget to ₹25,000',
    },
    {
      id: 'aud-3',
      eventId,
      timestamp: '2026-09-23 18:00',
      actorName: 'Kumar',
      actorRole: 'event_admin' as const,
      action: 'ADVANCE_SETTLED',
      details: 'Settled Stage Decoration advance for Arun (₹30,000 received, ₹28,400 spent, ₹1,600 returned)',
    },
  ];

  return {
    id: eventId,
    orgId: DEMO_ORGANIZATION.id,
    orgName: DEMO_ORGANIZATION.name,
    name: 'TECHNOVA 2026',
    description: 'National Level Technical Symposium & Cultural College Fest',
    destination: 'University Campus, Chennai',
    startDate: '2026-09-24',
    endDate: '2026-09-26',
    code: 'X7K9P2',
    currency: 'INR',
    status: 'active' as const,
    createdBy: DEMO_USER.id,
    createdAt: '2026-09-01T10:00:00Z',
    updatedAt: '2026-09-24T12:30:00Z',
    teams,
    members,
    incomeRecords,
    budgets,
    expenses,
    advances,
    reimbursements,
    vendors,
    auditLogs,
    settlements: [],
  };
}

export function createPondicherryDemoTrip(): EventModel {
  const eventId = 'evt-pondy-2026';

  const teams = [
    { id: 'tm-iv-1', eventId, name: 'Travel & Transport', budget: 20000 },
    { id: 'tm-iv-2', eventId, name: 'Food & Meals', budget: 15000 },
    { id: 'tm-iv-3', eventId, name: 'Stay & Villa', budget: 25000 },
  ];

  const members = [
    { id: 'mem-p1', eventId, userId: DEMO_USER.id, name: 'Eren', color: getMemberColor(0), role: 'event_admin' as const, joinedAt: '2026-09-20' },
    { id: 'mem-p2', eventId, name: 'Arun', color: getMemberColor(1), role: 'member' as const, joinedAt: '2026-09-20' },
    { id: 'mem-p3', eventId, name: 'Priya', color: getMemberColor(2), role: 'member' as const, joinedAt: '2026-09-20' },
    { id: 'mem-p4', eventId, name: 'Bala', color: getMemberColor(3), role: 'member' as const, joinedAt: '2026-09-20' },
    { id: 'mem-p5', eventId, name: 'Rahul', color: getMemberColor(4), role: 'member' as const, joinedAt: '2026-09-20' },
    { id: 'mem-p6', eventId, name: 'Divya', color: getMemberColor(5), role: 'member' as const, joinedAt: '2026-09-20' },
  ];

  const incomeRecords = [
    {
      id: 'inc-p1',
      eventId,
      amount: 60000,
      source: 'Student Trip Contribution (₹10,000 x 6)',
      category: 'Registration Fees' as const,
      date: '2026-09-20',
      description: 'Equal contribution collected from all 6 members for IV Pondicherry trip',
      addedBy: 'Eren',
      status: 'received' as const,
      createdAt: '2026-09-20T10:00:00Z',
    },
  ];

  const allMembersForSplit = members.map((m) => ({ id: m.id, name: m.name }));
  const getSplits = (amt: number) => calculateEqualSplits(amt, allMembersForSplit);

  const expenses = [
    {
      id: 'exp-p1',
      eventId,
      amount: 4800,
      currency: 'INR',
      merchant: 'ZoomCars Chennai',
      category: 'Transport',
      date: '2026-09-22',
      description: 'Innova Crysta cab from Chennai Airport to Pondicherry',
      notes: 'Highway tolls included',
      paidByMemberId: 'mem-p1',
      paidByMemberName: 'Eren',
      paymentSource: 'personal_money' as const,
      approvalStatus: 'approved' as const,
      splitMethod: 'equal' as const,
      splits: getSplits(4800),
      createdBy: 'Eren',
      createdAt: '2026-09-22T11:30:00Z',
      updatedAt: '2026-09-22T11:30:00Z',
    },
    {
      id: 'exp-p2',
      eventId,
      amount: 1840,
      currency: 'INR',
      merchant: 'ABC Restaurant Promenade',
      category: 'Food',
      date: '2026-09-22',
      description: 'Dinner for the crew at ABC Restaurant by the beach',
      notes: '6 meals, lemon soda, seafood thali',
      paidByMemberId: 'mem-p2',
      paidByMemberName: 'Arun',
      paymentSource: 'personal_money' as const,
      approvalStatus: 'approved' as const,
      splitMethod: 'equal' as const,
      splits: getSplits(1840),
      ocrData: {
        merchant: 'ABC Restaurant',
        amount: 1840,
        date: '2026-09-22',
        tax: 165,
        category: 'Food',
        items: [
          { name: 'Special Seafood Thali (x3)', price: 900, quantity: 3 },
          { name: 'Chicken Biryani (x3)', price: 720, quantity: 3 },
          { name: 'Fresh Lime Soda (x4)', price: 220, quantity: 4 },
        ],
      },
      createdBy: 'Arun',
      createdAt: '2026-09-22T21:45:00Z',
      updatedAt: '2026-09-22T21:45:00Z',
    },
    {
      id: 'exp-p3',
      eventId,
      amount: 12000,
      currency: 'INR',
      merchant: 'Ocean Spray Resort & Villa',
      category: 'Accommodation',
      date: '2026-09-23',
      description: '3-bedroom beachfront pool villa accommodation for 2 nights',
      notes: 'Paid by Rahul from personal money',
      paidByMemberId: 'mem-p5',
      paidByMemberName: 'Rahul',
      paymentSource: 'personal_money' as const,
      approvalStatus: 'approved' as const,
      splitMethod: 'equal' as const,
      splits: getSplits(12000),
      createdBy: 'Rahul',
      createdAt: '2026-09-23T10:15:00Z',
      updatedAt: '2026-09-23T10:15:00Z',
    },
  ];

  return {
    id: eventId,
    orgId: DEMO_ORGANIZATION.id,
    orgName: DEMO_ORGANIZATION.name,
    name: 'College IV – Pondicherry 2026',
    description: '5-Day Department Industrial Visit & Beach Trip',
    destination: 'Pondicherry, India',
    startDate: '2026-09-22',
    endDate: '2026-09-26',
    code: 'IVPND6',
    currency: 'INR',
    status: 'active' as const,
    createdBy: DEMO_USER.id,
    createdAt: '2026-09-20T10:00:00Z',
    updatedAt: '2026-09-24T12:00:00Z',
    teams,
    members,
    incomeRecords,
    budgets: [
      { id: 'b-p1', eventId, category: 'Transport', allocatedAmount: 20000 },
      { id: 'b-p2', eventId, category: 'Food', allocatedAmount: 15000 },
      { id: 'b-p3', eventId, category: 'Accommodation', allocatedAmount: 25000 },
    ],
    expenses,
    advances: [],
    reimbursements: [],
    vendors: [],
    auditLogs: [],
    settlements: [],
  };
}
